// AUTO-GENERATED by ops/tools/gen_tokens.py (the canonical palette). Do not edit by hand.
// The Wear OS module is Kotlin and can read neither tokens.ts nor OKLCH, so the
// SAME generator that writes tokens.ts for the phone writes these Color values
// for the watch. Editing this file by hand re-creates the drift it exists to
// prevent: change ops/tools/gen_tokens.py and re-run
//   py -3.12 ops/tools/gen_tokens.py
// Only the DARK theme is emitted - a watch has no light mode here.

package app.helmdeck.wear

import androidx.compose.ui.graphics.Color
import androidx.wear.compose.material3.ColorScheme

object WearTokens {
    val layer1 = Color(0xFF181A1BL)
    val layer1Hover = Color(0xFF1D1F20L)
    val borderSubtle = Color(0xFF222425L)
    val borderStrong = Color(0xFF36393AL)
    val txtPrimary = Color(0xFFE4E6E6L)
    val txtSecondary = Color(0xFFCACDCEL)
    val txtTertiary = Color(0xFFAFB3B6L)
    val txtPlaceholder = Color(0xFF959A9DL)
    val accent = Color(0xFF2396E5L)
    val accentTxt = Color(0xFF2396E5L)
    val brand700 = Color(0xFF6CB2ECL)
    val accent2 = Color(0xFF967AF0L)
    val ok = Color(0xFF5CB572L)
    val warn = Color(0xFFE59C4BL)
    val danger = Color(0xFFEA6A66L)
    val ai = Color(0xFF3D9BD6L)
    val human = Color(0xFF9B87E8L)
    val glass = Color(0x611B1D1EL)
    val glassBorder = Color(0x21FFFFFFL)
    val glow1 = Color(0x570093D8L)
    val glow2 = Color(0x429776FBL)
    val backdrop = Color(0x99000000L)
    val transparentHover = Color(0x1AFFFFFFL)
    val neutral100 = Color(0xFF141515L)
    val neutral200 = Color(0xFF181A1BL)
    val neutral300 = Color(0xFF1D1F20L)
    val neutral400 = Color(0xFF222425L)
    val neutral600 = Color(0xFF36393AL)
    val neutral900 = Color(0xFF959A9DL)
    val neutral1100 = Color(0xFFCACDCEL)
    val neutral1200 = Color(0xFFE4E6E6L)
    val canvas = Color(0xFF0E0F10L)
    val surface1 = Color(0xFF141515L)
    val surface2 = Color(0xFF181A1BL)
    val layer2 = Color(0xFF1D1F20L)
    val layer2Hover = Color(0xFF222425L)
}

/** Domain value -> brand colour, generated from the SAME table the
 *  phone's laneColor()/statusColor() use. No surface re-decides this. */
object WearSemantics {
    fun lane(value: String?): Color = when (value) {
        "backlog" -> WearTokens.txtTertiary
        "working" -> WearTokens.ai
        "review" -> WearTokens.human
        "done" -> WearTokens.ok
        else -> WearTokens.txtTertiary
    }

    fun status(value: String?): Color = when (value) {
        "queued" -> WearTokens.txtTertiary
        "running" -> WearTokens.ai
        "needs_you" -> WearTokens.warn
        "submitted" -> WearTokens.human
        "accepted" -> WearTokens.ok
        "bounced" -> WearTokens.danger
        "done" -> WearTokens.ok
        "failed" -> WearTokens.danger
        else -> WearTokens.txtTertiary
    }
}

/** The brand palette mapped onto Wear Material3's colour roles. The
 *  mapping itself is data in ops/tools/gen_tokens.py (WEAR_ROLE), so
 *  "which HelmDeck colour is the primary action" is decided in one
 *  place for every surface.
 *
 *  `background` is the one deliberate non-token: pure black, because a
 *  watch is OLED and an unlit pixel costs nothing. The brand's dark
 *  surfaces still carry the identity - they paint the cards. */
val HelmDeckWearColors = ColorScheme(
        primary = WearTokens.accent,
        primaryDim = WearTokens.ai,
        onPrimary = WearTokens.neutral100,
        primaryContainer = WearTokens.layer2,
        onPrimaryContainer = WearTokens.brand700,
        secondary = WearTokens.accent2,
        secondaryDim = WearTokens.human,
        onSecondary = WearTokens.neutral100,
        secondaryContainer = WearTokens.layer2,
        onSecondaryContainer = WearTokens.human,
        tertiary = WearTokens.ai,
        tertiaryDim = WearTokens.ai,
        onTertiary = WearTokens.neutral100,
        tertiaryContainer = WearTokens.layer2,
        onTertiaryContainer = WearTokens.ai,
        surfaceContainerLow = WearTokens.canvas,
        surfaceContainer = WearTokens.surface1,
        surfaceContainerHigh = WearTokens.surface2,
        onSurface = WearTokens.txtPrimary,
        onSurfaceVariant = WearTokens.txtSecondary,
        outline = WearTokens.borderStrong,
        outlineVariant = WearTokens.borderSubtle,
        onBackground = WearTokens.txtPrimary,
        error = WearTokens.danger,
        errorDim = WearTokens.danger,
        onError = WearTokens.neutral100,
    background = Color(0xFF000000L),
)
