# -*- coding: utf-8 -*-
"""Generate src/static.js from the constants in ../relay.py (PAIR_HTML,
PRIVACY_HTML, ASSETLINKS) so the worker serves the SAME pairing page, privacy
policy and App Links fingerprints as the Python relay - one source of truth,
no hand-copied HTML drifting. Run by ops/deploy/publish_relay_worker.sh."""
import io, json, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.dirname(HERE))
os.environ.setdefault("HELMDECK_RELAY_PORT", "0")
import relay  # noqa: E402

pair = relay.PAIR_HTML
# relay.py substitutes __C__ raw in both places; the worker escapes per context
assert pair.count("__C__") == 2, "PAIR_HTML placeholder count changed - update gen_static.py"
pair = pair.replace('href="helmdeck://pair?c=__C__"', 'href="helmdeck://pair?c=__C_ATTR__"', 1)
pair = pair.replace('location.replace("helmdeck://pair?c=__C__")', 'location.replace(__C_JS__)', 1)
assert "__C__" not in pair

out = (
    "// GENERATED by gen_static.py from surfaces/relay/relay.py - do not edit.\n"
    "export const PAIR_HTML = " + json.dumps(pair, ensure_ascii=False) + ";\n"
    "export const PRIVACY_HTML = " + json.dumps(relay.PRIVACY_HTML, ensure_ascii=False) + ";\n"
    "export const ASSETLINKS = " + json.dumps(relay.ASSETLINKS, ensure_ascii=False, indent=1) + ";\n"
)
dst = os.path.join(HERE, "src", "static.js")
io.open(dst, "w", encoding="utf-8", newline="\n").write(out)
print("wrote", dst, len(out), "bytes")
