// Scope Android cleartext HTTP to the direct-LAN hosts ONLY (pays debt
// [android-cleartext-lan]). Replaces the hand-added, app-wide
// android:usesCleartextTraffic="true" with a network-security-config:
// cleartext stays BLOCKED for every host except the ones the app's direct
// mode actually talks to. Android's NSC cannot express IP ranges (no
// RFC1918 wildcard), so the scope is an explicit host list:
//
//   defaults: 10.0.2.2 (emulator->host), localhost, 127.0.0.1 (adb reverse)
//   extras:   app.json -> plugins -> ["./plugins/withLanCleartext",
//             {"hosts": ["192.168.1.50"]}]  <- the PC's LAN IP for real-phone
//             direct mode (needs an APK rebuild; surfaces/relay/HTTPS paths unaffected)
//
// The same file serves both build paths, so the config cannot drift:
//   - `expo prebuild`: normal config plugin (registered in app.json).
//   - hand-managed surfaces/app/android (what ops/deploy/build_apk.sh actually builds):
//     `node app/plugins/withLanCleartext.js surfaces/app/android` patches the manifest
//     and writes the res/xml file, reading hosts from app.json. Idempotent.

const RES_XML = "network_security_config";
const DEFAULT_HOSTS = ["10.0.2.2", "localhost", "127.0.0.1"];

function hostsFrom(props) {
  const extra = (props && props.hosts) || [];
  return [...new Set([...DEFAULT_HOSTS, ...extra.map((h) => String(h).trim()).filter(Boolean)])];
}

function xmlFor(hosts) {
  const domains = hosts
    .map((h) => `        <domain includeSubdomains="false">${h}</domain>`)
    .join("\n");
  return `<?xml version="1.0" encoding="utf-8"?>
<!-- generated by app/plugins/withLanCleartext.js - edit hosts in app.json, not here -->
<network-security-config>
    <base-config cleartextTrafficPermitted="false" />
    <domain-config cleartextTrafficPermitted="true">
${domains}
    </domain-config>
</network-security-config>
`;
}

// String-level manifest patch shared by the CLI path; the prebuild path does
// the same two changes on the parsed manifest object below.
function patchManifestXml(xml) {
  let out = xml.replace(/\s*android:usesCleartextTraffic="[^"]*"/g, "");
  if (!out.includes("android:networkSecurityConfig=")) {
    out = out.replace(
      /<application\b/,
      `<application android:networkSecurityConfig="@xml/${RES_XML}"`
    );
  }
  return out;
}

// --- expo prebuild path -----------------------------------------------------
function withLanCleartext(config, props) {
  // lazy require: the CLI path below must work with bare node (no node_modules)
  const { withAndroidManifest, withDangerousMod } = require("expo/config-plugins");
  const fs = require("fs");
  const path = require("path");
  const hosts = hostsFrom(props);

  config = withAndroidManifest(config, (c) => {
    const app = (c.modResults.manifest.application || [])[0];
    if (app && app.$) {
      app.$["android:networkSecurityConfig"] = `@xml/${RES_XML}`;
      delete app.$["android:usesCleartextTraffic"];
    }
    return c;
  });

  return withDangerousMod(config, [
    "android",
    (c) => {
      const dir = path.join(c.modRequest.platformProjectRoot, "app", "src", "main", "res", "xml");
      fs.mkdirSync(dir, { recursive: true });
      fs.writeFileSync(path.join(dir, `${RES_XML}.xml`), xmlFor(hosts));
      return c;
    },
  ]);
}

// --- hand-managed android/ path (ops/deploy/build_apk.sh) -----------------------
function applyToAndroidDir(androidDir) {
  const fs = require("fs");
  const path = require("path");
  const appJson = JSON.parse(
    fs.readFileSync(path.join(__dirname, "..", "app.json"), "utf8")
  );
  const entry = (appJson.expo.plugins || []).find(
    (p) => Array.isArray(p) && /withLanCleartext/.test(p[0])
  );
  const hosts = hostsFrom(entry && entry[1]);

  const manifest = path.join(androidDir, "app", "src", "main", "AndroidManifest.xml");
  const before = fs.readFileSync(manifest, "utf8");
  const after = patchManifestXml(before);
  if (after !== before) fs.writeFileSync(manifest, after);

  const xmlDir = path.join(androidDir, "app", "src", "main", "res", "xml");
  fs.mkdirSync(xmlDir, { recursive: true });
  fs.writeFileSync(path.join(xmlDir, `${RES_XML}.xml`), xmlFor(hosts));
  return { hosts, changedManifest: after !== before };
}

module.exports = withLanCleartext;
module.exports.hostsFrom = hostsFrom;
module.exports.xmlFor = xmlFor;
module.exports.patchManifestXml = patchManifestXml;
module.exports.applyToAndroidDir = applyToAndroidDir;

if (require.main === module) {
  const target = process.argv[2];
  if (!target) {
    console.error("usage: node app/plugins/withLanCleartext.js <path-to-android-dir>");
    process.exit(2);
  }
  const r = applyToAndroidDir(target);
  console.log(
    `[withLanCleartext] cleartext scoped to: ${r.hosts.join(", ")}` +
      (r.changedManifest ? " (manifest patched)" : " (manifest already ok)")
  );
}
