# -*- coding: utf-8 -*-
"""The macOS desktop build contract - the parts a Windows box CAN prove.

The build itself only runs on macOS (codesign/hdiutil/notarytool live nowhere
else), so this test does not pretend to be a build. It locks the handful of
decisions that are easy to break from here and expensive to discover on a
runner twenty minutes into a job - each one a real failure mode, not a
restatement of the YAML:

  1. dmg AND zip, both arches. Dropping zip silently kills macOS auto-update:
     Squirrel.Mac can only apply a zipped .app, never a .dmg.
  2. notarize stays FALSE in the committed config. Flipping it on would make
     every secret-less build (a fork PR, a first CI run) fail at the notary
     step instead of producing an honest unsigned app.
  3. The entitlements files exist, parse, and carry disable-library-validation
     - without it a hardened HelmDeck cannot spawn the Python daemon or the
     `claude` CLI, which is the whole app.
  4. The mac icon is TRACKED and 1024x1024. icon.ico is git-ignored and
     regenerated by Pillow; if mac copied that pattern, CI would need Pillow.
  5. build-mac.sh refuses to run off macOS and passes notarize as an OBJECT
     (`-c.mac.notarize.teamId=...`) - `=true` arrives as the string "true",
     truthy but team-less.

Self-sandboxing: pure file reads, no daemon, no network, no node."""
import os
import plistlib
import re
import struct

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
DESK = os.path.join(ROOT, "surfaces", "desktop")

_fails = []


def check(cond, msg):
    print(("  ok    " if cond else "  FAIL  ") + msg)
    if not cond:
        _fails.append(msg)


def read(*parts):
    with open(os.path.join(*parts), encoding="utf-8") as f:
        return f.read()


print("macOS desktop build target")

cfg_text = read(DESK, "electron-builder.yml")

# -- 1. targets: dmg + zip, arm64 + x64 -------------------------------------
# PyYAML is not a hard dependency of this repo, so parse structurally when it
# is there and fall back to the raw text when it is not - the assertions below
# are the same either way.
try:
    import yaml
    cfg = yaml.safe_load(cfg_text)
except ImportError:
    cfg = None

if cfg is not None:
    mac = cfg.get("mac") or {}
    targets = {t.get("target"): set(t.get("arch") or []) for t in (mac.get("target") or [])}
    check(targets.get("dmg") == {"arm64", "x64"},
          "mac dmg target covers arm64 AND x64 (got %s)" % (targets.get("dmg"),))
    check(targets.get("zip") == {"arm64", "x64"},
          "mac zip target covers arm64 AND x64 - Squirrel.Mac cannot update from a "
          "dmg (got %s)" % (targets.get("zip"),))
    check(mac.get("hardenedRuntime") is True,
          "hardenedRuntime is on (notarization refuses anything else)")
    check(mac.get("notarize") is False,
          "notarize is FALSE in the committed config - build-mac.sh turns it on "
          "per-build, so a secret-less build still succeeds")
    check(mac.get("entitlements") == "build/entitlements.mac.plist"
          and mac.get("entitlementsInherit") == "build/entitlements.mac.inherit.plist",
          "both entitlements files are wired (custom ones REPLACE the defaults)")
    check((mac.get("icon") or "").endswith(".png"),
          "mac icon is the tracked PNG, converted to .icns at build time")
    check("${arch}" in (mac.get("artifactName") or ""),
          "mac artifactName carries ${arch} - two arches would otherwise "
          "overwrite each other")
    # the Windows path must survive untouched
    win = cfg.get("win") or {}
    check([t.get("target") for t in (win.get("target") or [])] == ["nsis"],
          "the Windows NSIS target is still intact")
else:
    check("target: dmg" in cfg_text and "target: zip" in cfg_text,
          "mac dmg + zip targets present (raw text - PyYAML absent)")
    check("notarize: false" in cfg_text,
          "notarize is FALSE in the committed config (raw text)")
    check("hardenedRuntime: true" in cfg_text, "hardenedRuntime is on (raw text)")

# -- 2. entitlements ---------------------------------------------------------
NEEDED = "com.apple.security.cs.disable-library-validation"
for name, extra in (("entitlements.mac.plist", None),
                    ("entitlements.mac.inherit.plist", "com.apple.security.inherit")):
    path = os.path.join(DESK, "build", name)
    if not os.path.exists(path):
        check(False, "%s exists" % name)
        continue
    with open(path, "rb") as f:
        try:
            ent = plistlib.load(f)
        except Exception as e:                       # a malformed plist fails codesign
            check(False, "%s is valid plist XML (%s)" % (name, e))
            continue
    check(ent.get("com.apple.security.cs.allow-jit") is True,
          "%s grants allow-jit (Electron cannot start hardened without it)" % name)
    check(ent.get(NEEDED) is True,
          "%s grants disable-library-validation - HelmDeck spawns python3 and "
          "claude, code it did not sign" % name)
    if extra:
        check(ent.get(extra) is True, "%s grants %s" % (name, extra))

# -- 3. the mac icon is tracked and the right shape --------------------------
icon = os.path.join(DESK, "assets", "icon-mac-1024.png")
check(os.path.exists(icon), "surfaces/desktop/assets/icon-mac-1024.png is committed "
                            "(unlike icon.ico, so CI needs no Pillow)")
if os.path.exists(icon):
    with open(icon, "rb") as f:
        head = f.read(24)
    # PNG IHDR: 8-byte signature, 4-byte length, 'IHDR', width, height
    ok_sig = head[:8] == b"\x89PNG\r\n\x1a\n" and head[12:16] == b"IHDR"
    w, h = struct.unpack(">II", head[16:24]) if ok_sig else (0, 0)
    check(ok_sig and w == h == 1024,
          "the mac icon is a 1024x1024 PNG (electron-builder rejects smaller "
          "for .icns) - got %sx%s" % (w, h))
    gitignore = read(DESK, ".gitignore")
    check("icon-mac" not in gitignore,
          "the mac icon is NOT git-ignored - a runner cannot regenerate it")

# -- 4. build-mac.sh's two load-bearing lines --------------------------------
sh = read(DESK, "build-mac.sh")
check(re.search(r'uname -s.*Darwin|Darwin.*uname -s', sh) is not None,
      "build-mac.sh refuses to run off macOS instead of failing obscurely")
check("-c.mac.notarize.teamId=" in sh,
      "notarize is passed as an OBJECT - `-c.mac.notarize=true` reaches "
      "electron-builder as the STRING \"true\", truthy but team-less")
check("CSC_IDENTITY_AUTO_DISCOVERY=false" in sh,
      "no identity => auto-discovery off, so the build goes UNSIGNED instead "
      "of dying on an empty keychain")

# -- 5. the runner that actually builds it -----------------------------------
wf_path = os.path.join(ROOT, ".github", "workflows", "desktop-mac.yml")
check(os.path.exists(wf_path), ".github/workflows/desktop-mac.yml exists - the "
                               "owner's box is Windows, so CI is the only builder")
if os.path.exists(wf_path):
    wf = read(wf_path)
    check(re.search(r"runs-on:\s*macos-", wf) is not None, "the job runs on a macOS runner")
    check("build-mac.sh" in wf, "the workflow drives the same script a Mac would")
    check("latest-mac.yml" in wf,
          "the workflow keeps latest-mac.yml - the auto-update feed, not a build leftover")

# -- 6. the source publish the runner depends on -----------------------------
# The workflow can only run once the source is IN the public repo that already
# hosts the releases. Two things about that push are silent regressions if
# someone "tidies" them, so they are pinned here rather than discovered live.
pub = os.path.join(ROOT, "ops", "deploy", "publish_source.sh")
check(os.path.exists(pub), "ops/deploy/publish_source.sh exists - the audited push "
                           "that gives the macOS runner something to check out")
if os.path.exists(pub):
    src = read(pub)
    check("--all" not in src.split("git push")[-1],
          "the push is single-branch - `--all` would hit GitHub's 100 MB hard "
          "limit on the parked wip-expo-migration release binaries")
    check("git@github.com:" in src,
          "the remote is SSH - the owner's gh token has no `workflow` scope, so "
          "an HTTPS push touching .github/workflows/ is rejected")

readme = read(ROOT, "README.md")
check("## Downloads" in readme,
      "the root README is the PUBLIC product page (Play links, SmartScreen "
      "note) - pushing the internal map here would replace a live page")
check(os.path.exists(os.path.join(ROOT, "ops", "docs", "repo-map.md")),
      "the internal repo map lives at ops/docs/repo-map.md")

print("FAILURES: %d" % len(_fails))
raise SystemExit(1 if _fails else 0)
