#!/usr/bin/env bash
# Build the signed release AAB (Play Store artifact) for the PHONE module.
#
# This is build_apk.sh's twin. Everything before the gradle line is IDENTICAL
# and deliberately so: DEPLOY.md 2 records that calling gradle by hand skips
# the prebuild + the seven config plugins + the version sync SILENTLY - the
# build goes green and the artifact is wrong (measured 2026-08-17: a 52-minute
# build stamped 1.0.2/38 while app.json already said 1.0.8/44). An AAB that
# goes to production is the LAST place to re-learn that, so this script copies
# the whole preamble rather than shelling out to a shortcut.
#
# Differences from build_apk.sh:
#   - `:app:bundleRelease` instead of `:app:assembleRelease`
#   - no emulator smoke (an .aab cannot be `adb install`ed)
#   - no relay distribution (the relay serves the sideload APK, not the Play AAB)
#   - withMetaDat.js is DELIBERATELY SKIPPED (2026-09-01). It wires the glasses
#     CAMERA (GlassCameraService, FOREGROUND_SERVICE_CONNECTED_DEVICE). That
#     permission was removed from app.json's `plugins` for the Play submission
#     specifically because glasses.capture()/stopCamera() have no UI trigger
#     anywhere in surfaces/app/src - Google's foreground-service declaration
#     needs a real, demoable feature, and there isn't one yet (see
#     ops/docs/store/DATA_SAFETY.md, PLAY_STORE_RELEASE.md §6.1). Re-applying
#     it here unconditionally, the way build_apk.sh correctly still does for
#     the sideload APK (which Play never reviews), would silently put Google
#     right back in front of the same undeclarable permission. Re-add the call
#     below once the camera feature has a real screen AND withMetaDat is back
#     in app.json's plugins array - not before.
set -o pipefail
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"; cd "$ROOT"

# JDK 17 - RN 0.86 / Expo 57 need it (Java 8 fails). Microsoft OpenJDK install.
JAVA_HOME="$(ls -d '/c/Program Files/Microsoft/jdk-17'* 2>/dev/null | head -1)"
[ -z "$JAVA_HOME" ] && { echo "[build_aab] JDK 17 missing - winget install Microsoft.OpenJDK.17"; exit 1; }
export JAVA_HOME
export ANDROID_HOME="${ANDROID_HOME:-$HOME/AppData/Local/Android/Sdk}"
export PATH="/c/Program Files/nodejs:$JAVA_HOME/bin:$ANDROID_HOME/platform-tools:$PATH"

# ANDROID BUILD MUTEX - same lock, same position (before `gradlew --stop`, which
# stops every Gradle daemon of this user and would otherwise kill a running
# build). See build_apk.sh for the full reasoning.
. "$(dirname "$0")/build_lock.sh"
android_build_lock "build_aab.sh :app:bundleRelease (${HELMDECK_CARD:-manuell/kein Karten-Kontext})"

( cd surfaces/app/android 2>/dev/null && {
    ./gradlew --stop >/dev/null 2>&1
    for _i in 1 2 3 4 5 6 7 8; do
      ./gradlew --status 2>/dev/null | grep -qiE "IDLE|BUSY" || break
      sleep 5
    done
    sleep 3
  } ) || true

echo "[build_aab] npm ci (sync node_modules with the lockfile)"
( cd surfaces/app && npm ci ) || { echo "[build_aab] npm ci FAILED"; exit 1; }

echo "[build_aab] expo prebuild --platform android --clean"
( cd surfaces/app && CI=1 ./node_modules/.bin/expo prebuild --platform android --clean ) \
  || { echo "[build_aab] expo prebuild FAILED"; exit 1; }

# lintVitalAnalyzeRelease OOMs on the template's 512m Metaspace; gradle.properties
# is regenerated by the prebuild above, so patch it every build.
sed -i 's/-XX:MaxMetaspaceSize=512m/-XX:MaxMetaspaceSize=1024m/' \
  surfaces/app/android/gradle.properties
grep -q "MaxMetaspaceSize=1024m" surfaces/app/android/gradle.properties \
  || { echo "[build_aab] Metaspace bump did not apply (template changed?)"; exit 1; }

# local.properties MUST use forward slashes (Java properties parser eats \).
printf 'sdk.dir=%s\n' "$(cygpath -m "$ANDROID_HOME" 2>/dev/null || echo "$ANDROID_HOME")" \
  > surfaces/app/android/local.properties

# The seven re-applies. android/ is git-ignored and regenerated from nothing by
# --clean, so each of these is the ONLY thing that puts its config back. Every
# one of them fails SILENTLY (green build, wrong artifact) if skipped.
node surfaces/app/plugins/withLanCleartext.js surfaces/app/android \
  || { echo "[build_aab] network-security-config apply FAILED"; exit 1; }
node surfaces/app/plugins/withReleaseSigning.js surfaces/app/android \
  || { echo "[build_aab] release-signing apply FAILED"; exit 1; }
node surfaces/app/plugins/withGlassVoice.js surfaces/app/android \
  || { echo "[build_aab] glass-voice manifest apply FAILED"; exit 1; }
# withMetaDat.js intentionally NOT called here - see the header comment.
node surfaces/app/plugins/withSherpaOnnx.js surfaces/app/android \
  || { echo "[build_aab] sherpa-onnx wiring apply FAILED"; exit 1; }
node surfaces/app/plugins/withUpdateUrl.js surfaces/app/android \
  || { echo "[build_aab] update-url manifest apply FAILED"; exit 1; }
node surfaces/app/plugins/withWearApp.js surfaces/app/android \
  || { echo "[build_aab] wear-module wiring apply FAILED"; exit 1; }

# read:packages credential for com.meta.wearable, needed at GRADLE time.
if [ -z "$GITHUB_TOKEN" ]; then
  GITHUB_TOKEN="$(gh auth token 2>/dev/null || true)"
  export GITHUB_TOKEN
  [ -n "$GITHUB_TOKEN" ] && echo "[build_aab] GITHUB_TOKEN derived from the gh CLI"
fi
if [ -z "$GITHUB_TOKEN" ] \
   && ! grep -q "github_token" surfaces/app/android/local.properties 2>/dev/null \
   && grep -q "com.meta.wearable" surfaces/app/android/app/build.gradle 2>/dev/null; then
  echo "[build_aab] NO read:packages CREDENTIAL - the Meta DAT artifacts cannot resolve."
  echo "[build_aab]   export GITHUB_TOKEN=\"\$(gh auth token)\""
  exit 1
fi

# Sync the hand-managed native version from app.json (versionName, versionCode,
# EXPO_RUNTIME_VERSION) so the artifact, its runtime version and the OTA target
# cannot drift. app.json is the single source of truth.
node -e '
  const fs = require("fs");
  const e = JSON.parse(fs.readFileSync("surfaces/app/app.json", "utf8")).expo;
  const ver = e.version, vc = String(e.android.versionCode);
  const g = "surfaces/app/android/app/build.gradle";
  fs.writeFileSync(g, fs.readFileSync(g, "utf8")
    .replace(/versionCode\s+\d+/, "versionCode " + vc)
    .replace(/versionName\s+"[^"]*"/, "versionName \"" + ver + "\""));
  const m = "surfaces/app/android/app/src/main/AndroidManifest.xml";
  fs.writeFileSync(m, fs.readFileSync(m, "utf8")
    .replace(/(EXPO_RUNTIME_VERSION"\s+android:value=")[^"]*(")/, "$1" + ver + "$2"));
  console.log("[build_aab] native version synced from app.json -> " + ver + " / " + vc);
' || { echo "[build_aab] native version sync FAILED"; exit 1; }

echo "[build_aab] gradle :app:bundleRelease (~10-15 min)"
# arm64-v8a ONLY (owner decree 2026-08-25): the 4-ABI default deterministically
# fails on armeabi-v7a (ninja 'build.ninja still dirty' in reanimated's CMake,
# 3/3). Scoped to :app so the never-built, unsigned :wear module that
# withWearApp.js just added to settings.gradle is not dragged in.
( cd surfaces/app/android && ./gradlew :app:bundleRelease -x lint --console=plain \
    -PreactNativeArchitectures=arm64-v8a ) \
  || { echo "[build_aab] AAB BUILD FAILED"; exit 1; }

AAB="surfaces/app/android/app/build/outputs/bundle/release/app-release.aab"
[ -f "$AAB" ] || { echo "[build_aab] no AAB produced"; exit 1; }
echo "[build_aab] AAB: $(du -h "$AAB" | cut -f1) -> $AAB"
echo "[build_aab] done"
